// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMediaManager.Data;

#nullable disable

namespace WebMediaManager.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260617022843_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WebMediaManager.Core.Domain.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Settings.AppSettings", b =>
                {
                    b.OwnsOne("WebMediaManager.Core.Settings.ArtworkSettings", "Artwork", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<bool>("DownloadFanart");

                            b1.Property<bool>("DownloadPoster");

                            b1.Property<string>("FanartFilename")
                                .IsRequired();

                            b1.Property<string>("PosterFilename")
                                .IsRequired();

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Artwork")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.NfoSettings", "Nfo", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<bool>("WriteEpisodeNfo");

                            b1.Property<bool>("WriteMovieNfo");

                            b1.Property<bool>("WriteTvShowNfo");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Nfo")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.ProviderSettings", "Providers", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<int>("PreferredMovieSource");

                            b1.Property<int>("PreferredTvSource");

                            b1.Property<string>("TmdbApiKey");

                            b1.Property<string>("TvdbApiKey");

                            b1.Property<string>("TvdbPin");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Providers")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.RenamePatternSettings", "RenamePatterns", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<string>("EpisodeFile")
                                .IsRequired();

                            b1.Property<string>("MovieFile")
                                .IsRequired();

                            b1.Property<string>("MovieFolder")
                                .IsRequired();

                            b1.Property<string>("SeasonFolder")
                                .IsRequired();

                            b1.Property<string>("ShowFolder")
                                .IsRequired();

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("RenamePatterns")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.Navigation("Artwork")
                        .IsRequired();

                    b.Navigation("Nfo")
                        .IsRequired();

                    b.Navigation("Providers")
                        .IsRequired();

                    b.Navigation("RenamePatterns")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
