// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMediaManager.Data;

#nullable disable

namespace WebMediaManager.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260621204354_AddActivityLog")]
    partial class AddActivityLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WebMediaManager.Core.Domain.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Artwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DownloadedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Kind");

                    b.ToTable("Artworks", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateScanned")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasNfo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Studios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Votes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("LibraryId", "MatchState");

                    b.ToTable("MediaItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TvShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Movie", b =>
                {
                    b.HasBaseType("WebMediaManager.Core.Domain.MediaItem");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoFilePath")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.TvShow", b =>
                {
                    b.HasBaseType("WebMediaManager.Core.Domain.MediaItem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TvShow");
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Artwork", b =>
                {
                    b.HasOne("WebMediaManager.Core.Domain.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Episode", b =>
                {
                    b.HasOne("WebMediaManager.Core.Domain.Season", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.MediaItem", b =>
                {
                    b.HasOne("WebMediaManager.Core.Domain.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Season", b =>
                {
                    b.HasOne("WebMediaManager.Core.Domain.TvShow", null)
                        .WithMany("Seasons")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMediaManager.Core.Settings.AppSettings", b =>
                {
                    b.OwnsOne("WebMediaManager.Core.Settings.ArtworkSettings", "Artwork", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<bool>("DownloadFanart");

                            b1.Property<bool>("DownloadPoster");

                            b1.Property<string>("FanartFilename")
                                .IsRequired();

                            b1.Property<string>("PosterFilename")
                                .IsRequired();

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Artwork")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.NfoSettings", "Nfo", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<bool>("WriteEpisodeNfo");

                            b1.Property<bool>("WriteMovieNfo");

                            b1.Property<bool>("WriteTvShowNfo");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Nfo")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.ProviderSettings", "Providers", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<int>("PreferredMovieSource");

                            b1.Property<int>("PreferredTvSource");

                            b1.Property<string>("TmdbApiKey");

                            b1.Property<string>("TvdbApiKey");

                            b1.Property<string>("TvdbPin");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("Providers")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("WebMediaManager.Core.Settings.RenamePatternSettings", "RenamePatterns", b1 =>
                        {
                            b1.Property<int>("AppSettingsId");

                            b1.Property<bool>("AutoRenameAfterMatch");

                            b1.Property<string>("EpisodeFile")
                                .IsRequired();

                            b1.Property<string>("MovieFile")
                                .IsRequired();

                            b1.Property<string>("MovieFolder")
                                .IsRequired();

                            b1.Property<string>("SeasonFolder")
                                .IsRequired();

                            b1.Property<string>("ShowFolder")
                                .IsRequired();

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1
                                .ToJson("RenamePatterns")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.Navigation("Artwork")
                        .IsRequired();

                    b.Navigation("Nfo")
                        .IsRequired();

                    b.Navigation("Providers")
                        .IsRequired();

                    b.Navigation("RenamePatterns")
                        .IsRequired();
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("WebMediaManager.Core.Domain.TvShow", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
